services:

  api:
    build:
      context: ./api
      args:
        BUILD_NUMBER: ${BUILD_NUMBER:-local}
        GIT_COMMIT: ${GIT_COMMIT:-local}
    container_name: final-api
    environment:
      PORT: 3000
      BUILD_NUMBER: ${BUILD_NUMBER:-local}
      GIT_COMMIT: ${GIT_COMMIT:-local}
    networks:
      - final-network

  web:
    build:
      context: ./web
      args:
        BUILD_NUMBER: ${BUILD_NUMBER:-local}
        GIT_COMMIT: ${GIT_COMMIT:-local}
    container_name: final-web
    environment:
      PORT: 3000
      API_URL: http://api:3000
      BUILD_NUMBER: ${BUILD_NUMBER:-local}
      GIT_COMMIT: ${GIT_COMMIT:-local}
    ports:
      - "8085:3000"
    depends_on:
      - api
    networks:
      - final-network

networks:
  final-network: