services:
  api:
    image: jenkins-final-project-api:latest
    build:
      context: ./api
      args:
        BUILD_NUMBER: ${BUILD_NUMBER:-local}
        GIT_COMMIT: ${GIT_COMMIT:-local}
    networks:
      - final-network

  web:
    image: jenkins-final-project-web:latest
    build:
      context: ./web
      args:
        BUILD_NUMBER: ${BUILD_NUMBER:-local}
        GIT_COMMIT: ${GIT_COMMIT:-local}
    ports:
      - "8085:3000"
    environment:
      API_URL: http://wrong-api:3000
    depends_on:
      - api
    networks:
      - final-network

networks:
  final-network:
    name: final-network
    driver: bridge
